### ISSUE TITLE
Error with cdk version

### ISSUE THREAD

**Issue by rafaelbarioni** [mattymoomoo/aws-power-tuner-ui#50]
Hello.

I´m trying to deploy in my AWS account here, but I get error with CDK version.

`
Do you wish to deploy these changes (y/n)? y
PowerTunerInfraStack: deploying...
PowerTunerInfraStack: creating CloudFormation changeset...

 ❌  PowerTunerInfraStack failed: Error: Failed to create ChangeSet cdk-deploy-change-set on PowerTunerInfraStack: FAILED, Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [powerTuner] is invalid. User: arn:aws:sts::521916331075:assumed-role/AWSReservedSSO_Developers-1_f6c82285d21ec261/rafael.barioni@assertivainformacoes.com is not authorized to perform: serverlessrepo:CreateCloudFormationTemplate on resource: arn:aws:serverlessrepo:us-east-1:451282441545:applications/aws-lambda-power-tuning
    at C:\Users\rafael.barioni\git\aws-power-tuner-ui\cdk\node_modules\aws-cdk\lib\api\util\cloudformation.ts:265:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at waitFor (C:\Users\rafael.barioni\git\aws-power-tuner-ui\cdk\node_modules\aws-cdk\lib\api\util\cloudformation.ts:220:20)
    at waitForChangeSet (C:\Users\rafael.barioni\git\aws-power-tuner-ui\cdk\node_modules\aws-cdk\lib\api\util\cloudformation.ts:251:15)
    at prepareAndExecuteChangeSet (C:\Users\rafael.barioni\git\aws-power-tuner-ui\cdk\node_modules\aws-cdk\lib\api\deploy-stack.ts:337:32)
    at CdkToolkit.deploy (C:\Users\rafael.barioni\git\aws-power-tuner-ui\cdk\node_modules\aws-cdk\lib\cdk-toolkit.ts:209:24)
    at initCommandLine (C:\Users\rafael.barioni\git\aws-power-tuner-ui\cdk\node_modules\aws-cdk\lib\cli.ts:341:12)

NOTICES

19836   AWS CDK v1 has entered maintenance mode

        Overview: AWS CDK v1 has entered maintenance mode on June 1, 2022.
                  Migrate to AWS CDK v2 to continue to get the latest features
                  and fixes!

        Affected versions: framework: 1.*, cli: 1.*
`

I´m not very familiar with Node code.
How could I solve this issue, please?

Thanks a lot

**Comment by abhishekdipu** [comment]
I'm also getting the same error. Looks like CDK need to updated for this project.
<img width="1792" alt="Screenshot 2023-08-22 at 1 09 27 AM" src="https://github.com/mattymoomoo/aws-power-tuner-ui/assets/45310629/622dfc76-98a2-4f35-b6c1-b25c50fdb760">
